// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Clipper is an autogenerated mock type for the Clipper type
type Clipper struct {
	mock.Mock
}

// ReadAll provides a mock function with given fields:
func (_m *Clipper) ReadAll() (string, error) {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WriteAll provides a mock function with given fields: s
func (_m *Clipper) WriteAll(s string) error {
	ret := _m.Called(s)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(s)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
