// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// RpcClient is an autogenerated mock type for the RpcClient type
type RpcClient struct {
	mock.Mock
}

// Call provides a mock function with given fields: serviceMethod, args, reply
func (_m *RpcClient) Call(serviceMethod string, args interface{}, reply interface{}) error {
	ret := _m.Called(serviceMethod, args, reply)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, interface{}, interface{}) error); ok {
		r0 = rf(serviceMethod, args, reply)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
