// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// RpcServer is an autogenerated mock type for the RpcServer type
type RpcServer struct {
	mock.Mock
}

// HandleHTTP provides a mock function with given fields: _a0, _a1
func (_m *RpcServer) HandleHTTP(_a0 string, _a1 string) {
	_m.Called(_a0, _a1)
}

// Register provides a mock function with given fields: _a0
func (_m *RpcServer) Register(_a0 interface{}) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
