name: Build - Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.15
      uses: actions/setup-go@v1
      with:
        go-version: 1.15
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build Linux
      env:
        APP_TOKEN: ${{ secrets.AppToken }}
        APP_SECRET: ${{ secrets.AppSecret }}
      run: make build

    - name: Build Mac
      env:
        APP_TOKEN: ${{ secrets.AppToken }}
        APP_SECRET: ${{ secrets.AppSecret }}
      run: make buildmac

    - name: Build Linux/ARM
      env:
        APP_TOKEN: ${{ secrets.AppToken }}
        APP_SECRET: ${{ secrets.AppSecret }}
      run: make buildarm

    - name: Package
      run: make package

