name: Build - Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux-plus:
    name: Build Linux +
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.19
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Test
      run: make test

    - name: Build Linux
      run: make build

    - name: Build Linux/ARM
      run: make buildarm

  build-macos:
    name: Build Macos
    runs-on: macos-latest
    steps:
      - name: Set up Go 1.19
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Test
        run: make test

      - name: Build Macos
        run: make build

  build-windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - name: Set up Go 1.19
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Test
        run: make test

      - name: Build Windows
        run: make build